blueprint:
  name: Suivi d'un appareil via un capteur de courant
  description: 
    Crée une automation qui détecte si un appareil est en marche en fonction de son courant.

    Etape 1 creation d'un "sensor" energy

    
    
    **If you like my blueprints, and would like to show your support or just say thank you?** [Click Here](https://www.paypal.com/donate/?hosted_button_id=WAZS3QSDTPGA8) 🙂
    
    
    <details>
    <summary><b>The Automation Process:</b> 👈</summary>
      - **Actions:**
          - Tracks if an entity is manually turned ON and OFF, updating the toggle helper to reflect the control method.
          - If the entity is turned ON by an automation, the toggle helper remains unchanged.
      - **Auto OFF Options:**
          - Automatically turns off the target entity and toggle helper.
          - Automatically turns off the toggle helper.
    </details>
    
    
  domain: automation
  input:
    power_sensor:
      name: Capteur de courant
      description: Sélectionne le capteur de courant de l'appareil.
      selector:
        entity:
          domain: sensor
    binary_sensor_name:
      name: Nom du capteur binaire
      description: Entité du capteur binaire à mettre à jour.
      selector:
        entity:
          domain: binary_sensor
    threshold:
      name: Seuil de détection (A)
      description: Valeur minimale de courant pour considérer que l'appareil est en marche.
      default: 0.030
      selector:
        number:
          min: 0.005
          max: 10
          step: 0.010
          unit_of_measurement: "A"
    delay_from_off:
      name: Délai avant arrêt
      description: Temps en minutes avant que l'appareil soit considéré comme éteint.
      default: 5  # 5 minutes
      selector:
        number:
          min: 0.0
          max: 60.0
          step: 1.0
          unit_of_measurement: "min"
    icon_:
      name: Icône 
      description: Icône de  l'appareil 
      default: "mdi:power-plug"
      selector:
        text: {}

mode: restart

trigger:
  - platform: state
    entity_id: !input power_sensor

condition: []

action:
  - variables:
      power_sensor: !input power_sensor
      threshold: !input threshold
      delay_from_off: !input delay_from_off
  - service: persistent_notification.create
    data:
      title: "Debug - Appareil suivi"
      message: "Capteur: {{ states(power_sensor) }}A / Seuil: {{ threshold }}A "
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(power_sensor) | float(0) >  threshold }}"
        sequence:
          - service: homeassistant.turn_on
            entity_id: !input binary_sensor_name
          - service: homeassistant.update_entity
            entity_id: !input binary_sensor_name

      - conditions:
          - condition: template
            value_template: "{{ states(power_sensor) | float(0) <=  threshold }}"
        sequence:
          - delay: 
              seconds: "{{ delay_from_off | int * 60 }}"
          - service: homeassistant.turn_off
            entity_id: !input binary_sensor_name
          - service: homeassistant.update_entity
            entity_id: !input binary_sensor_name
sensor:
  icon: "{{ icon_on }}"
  availability: "{{ has_value(binary_sensor_name) }}"
